version: 2
jobs:
  build:
    working_directory: &working_directory /usr/src/cottontail
    docker:
      - image: elixir:1.6-alpine
      - image: rabbitmq:3.6-alpine
    environment:
      AMQP_URL: "amqp://guest:guest@localhost:5672"
      MIX_ENV: test
    steps:
      - checkout:
          path: *working_directory
      - restore_cache:
          keys:
            - v1-cottontail-{{ checksum "mix.lock" }}-{{ .Branch }}-{{ .Revision }}
            - v1-cottontail-{{ checksum "mix.lock" }}-{{ .Branch }}
      - run:
          name: Install Image
          command: |
            set -eou pipefail
            apk update
            apk add --no-cache git build-base openssh ca-certificates curl
      - run:
          name: Install App
          command: |
            set -eou pipefail
            mix local.hex --force
            mix local.rebar --force
            mix deps.get
            mix deps.compile
            mix clean
      - save_cache:
          key: v1-cottontail-{{ checksum "mix.lock" }}-{{ .Branch }}-{{ .Revision }}
          paths:
            - /usr/src/cottontail/deps
            - /usr/src/cottontail/_build
            - /root/.hex/
            - /root/.mix/
            - /root/.cache/rebar3/
      - run:
          name: Lint
          command: |
            mix credo --strict
      - run:
          name: Test
          command: |
            mix coveralls.json
      - run:
          name: Upload Coverage
          command: |
            curl -s https://codecov.io/bash > .codecov
            chmod +x .codecov
            ./.codecov

workflows:
  version: 2
  cottontail:
    jobs:
      - build
